import { Inter } from "next/font/google";
import "./globals.css";
import NextUiProvider from "@/components/providers/NextUiProvider";
import ReduxProvider from "@/components/providers/ReduxProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ProtectedRoute from "@/components/RouteProtection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ReduxProvider>
            <ProtectedRoute>
              <NextUiProvider>
                <ToastContainer />
                {children}
              </NextUiProvider>
            </ProtectedRoute>
          </ReduxProvider>
      </body>
    </html>
  );
}
