import { Inter } from "next/font/google";
import "./globals.css";
import NextUiProvider from "@/components/providers/NextUiProvider";
import Header from "@/components/header/Header";
import TanstackQueryProvider from "@/components/providers/TanstackQueryProvider";
import ReduxProvider from "@/components/providers/ReduxProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQueryProvider>
          <ReduxProvider>
            <NextUiProvider>
              <ToastContainer />
              <Header />
              {children}
            </NextUiProvider>
          </ReduxProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
