import DashboardHeader from "@/components/header/DashboardHeader";
import SideBar from "@/components/sidebar/SideBar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <DashboardHeader />
      <div className="flex pt-12">
        <SideBar />
        <div className="pl-[320px] w-full">{children}</div>
      </div>
    </>
  );
}
